# Generated by Django 3.0.7 on 2020-06-25 08:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200624_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='user_name',
            field=models.CharField(max_length=100, validators=[users.models.validate_name]),
        ),
    ]
