# Generated by Django 3.0.7 on 2020-06-25 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200625_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='user_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must bot conatain numbers or characters', regex='^[a-zA-Z][a-zA-Z \\.]+[a-zA-Z]$')]),
        ),
    ]
