# Generated by Django 3.0.7 on 2020-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200622_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='user_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
