# Generated by Django 3.0.7 on 2020-06-25 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200625_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='user_mobile_no',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(code='invalid_mobileno', message='Mobile number must  conatain only numbers', regex='^[0-9]$')]),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='user_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must not conatain numbers or characters', regex='^[a-zA-Z][a-zA-Z \\.]+[a-zA-Z]$')]),
        ),
    ]
